InventoryManagement/force-app/main/default/objects/Custom_Product__c/Custom_Product__c.object-meta.xml
<CustomObject>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

InventoryManagement/force-app 2/main/default/objects/Custom_Product__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

InventoryManagement/force-app 2/main/default/classes/TestProduct.cls
@isTest
public class TestProduct {
@TestSetup
    Public static void MakeData() {
        TestHelper.MakeData();
    }
    
    @isTest
    public static void orderTriggerTest(){
        try{
            Test.startTest();
            List<Custom_Product__c> newProducts = [SELECT id, Name, Description__c, price__c from Custom_Product__c];
            
            delete newProducts;
            
            Test.stopTest(); 
        } Catch (DMLException e) {
            
        }
     
        List<Custom_Product__c> newProductsTest = [SELECT id, Name, Description__c, price__c from Custom_Product__c];
        
        System.assertEquals(2, newProductsTest.size());
        
    }
}