InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Outbound_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app 2/main/default/objects/Custom_Order__c/fields/Order_Date__c.field-meta.xml
<CustomField>
    <fullName>Order_Date__c</fullName>
    <label>Order Date</label>
    <type>Date</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/classes/NewOrderController.cls
public class NewOrderController {
    
    public List<SelectOption> ProductPicklist {
        get{
            List<Product2> tempProduct = new List<Product2>();
    		List<SelectOption> itemList = new List<SelectOption>();
    		tempProduct = [SELECT Name FROM Product2];
        
        	for (Product2 item: tempProduct){
            	itemList.add(new SelectOption(item.Id, item.Name));
        	}
        	return itemList;
            
        }
        set;
    }
    public String selectedProduct{get; set;}
    public Integer quantity{get;set;}
    public Date selectDate{get; set;}
    public String successStatement{get; set;}
    
    public void saveOrder(){
        Custom_Order__c newOrder = new Custom_Order__c();
        Contact getContact = [SELECT Name FROM Contact WHERE Name =: UserInfo.getName() LIMIT 1];
        newOrder.Product2__c = selectedProduct;
        newOrder.Contact__c = getContact.id;
        newOrder.Quantity__c = quantity;
        newOrder.Order_Date__c = selectDate;
        newOrder.Order_Status__c = 'pending';
        Database.SaveResult success = Database.insert(newOrder);
        if (success.isSuccess()){
            successStatement = 'Order submitted successfully!';
        }
        else{
            successStatement = 'Your order could not be sumbitted.';
        }
    }
}