InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/AddedToInventory__c.field-meta.xml
<CustomField>
    <fullName>AddedToInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Private field to add to inventory only once per order</description>
    <label>AddedToInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/RemovedFromInventory__c.field-meta.xml
<CustomField>
    <fullName>RemovedFromInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RemovedFromInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/force-app/main/default/classes/NewOrderControllerTest.cls
@isTest
public class NewOrderControllerTest {
	@testSetup
    public static void makeData(){
        List<Product2> testProductList = new List<Product2>();
        testProductList.add(new Product2(Name='Oatmeal', Description='test product'));
        testProductList.add(new Product2(Name='Coffee', Description='test product')); 
        insert testProductList;
        
        List<Custom_Order__c> testOrderList = new List<Custom_Order__c>();
        testOrderList.add(new Custom_Order__c (quantity__c=10, Product2__c=testProductList[0].Id, Order_Status__c='Delivered', AddedToInventory__c=True, RemovedFromInventory__c=True));
        testOrderList.add(new Custom_Order__c (quantity__c=10, Product2__c=testProductList[1].Id, Order_Status__c='Pending', AddedToInventory__c=True, RemovedFromInventory__c=True));
        insert testOrderList;
    }
    @isTest
    public static void listTest(){
        List<Product2> testList = [SELECT id, Name, Description from Product2];
        System.assertEquals(2, testList.size());
    }
    @isTest
    public static void saveOrderTest(){
        List<Custom_order__c> orderList = [SELECT id FROM Custom_order__c];
        System.assertEquals(2, orderList.size());
    }
}