InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>Outbound_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Estimated_Recieve_Date_End__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Recieve_Date_End__c</fullName>
    <label>Estimated Recieve Date End</label>
    <type>DateTime</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/Estimated_Recieve_Date_Start__c.field-meta.xml
<CustomField>
    <fullName>Estimated_Recieve_Date_Start__c</fullName>
    <label>Estimated Recieve Date Start</label>
    <type>DateTime</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/classes/EventCalanderControllerTest.cls
@isTest
public class EventCalanderControllerTest {
    @testSetup
    public static void makeData(){
        TestHelper.MakeData();
        
        Custom_Order__c customOrder = new Custom_Order__c();
        customOrder.Contact__c = [SELECT id FROM Contact LIMIT 1].id;
		customOrder.Product2__c = [SELECT id FROM Product2 LIMIT 1].id;
        customOrder.Quantity__c = 2;
        customOrder.Estimated_Recieve_Date_Start__c= DateTime.newInstance(2025, 2, 2, 1, 1, 1);
        customOrder.Estimated_Recieve_Date_End__c= DateTime.newInstance(2025, 2, 4, 1, 1, 1);
        insert customOrder;
    }
	@isTest
    public static void EventCalanderControllerTest(){
		Test.startTest();
        PageReference pageRef = Page.CalanderPage;
        Test.setCurrentPage(pageRef);
        EventCalanderController controller = new EventCalanderController();
		
        controller.yearToView = null;
        controller.monthToView = null;
		
        System.assertEquals(System.now().year(), controller.yearToView);
        System.assertEquals(System.now().month(), controller.monthToView);
        
        
        controller.yearToView = 2025;
        controller.monthToView = 2;
        controller.updateCalander();
        Integer year = controller.yearToView;
        Integer month = controller.monthToView;
        System.assertEquals(2025, year);
        System.assertEquals(2, month);
        System.assertEquals(new List<string>{'26 ' , '2 ' , '9 ' , '16 ' , '23 '}, controller.eventList.Sunday);
        
        Test.stopTest();
    }
}