InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/Custom_Inventory__c.object-meta.xml
<CustomObject>
    <label>Custom Inventory</label>
    <nameField>
        <displayFormat>Inventory-ID-{000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Inventories</relationshipLabel>
    <relationshipName>Custom_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/AddedToInventory__c.field-meta.xml
<CustomField>
    <fullName>AddedToInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Private field to add to inventory only once per order</description>
    <label>AddedToInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/RemovedFromInventory__c.field-meta.xml
<CustomField>
    <fullName>RemovedFromInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RemovedFromInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/force-app/main/default/classes/OrderClass.cls
public class OrderClass {
    
    public static void AdjustInventoryBasedOnTrigger(List<Custom_Order__c> added_orders) {
		List<String> products = new List<String>();
         for (Custom_Order__c CustomOrder : added_orders) {
            products.add(CustomOrder.product2__c);
         }
        List<Custom_Inventory__c> myInventory = [SELECT ID, quantity__c, product2__c FROM Custom_Inventory__c WHERE product2__c IN :products];
         for (Custom_Order__c CustomOrder : added_orders) {
             
             if (CustomOrder.Order_Status__c == 'Delivered' && CustomOrder.AddedToInventory__c == False) {
                 CustomOrder.AddedToInventory__c = True;
                 myInventory = InventoryClass.addToInventoryList(CustomOrder.Product2__c, CustomOrder.quantity__c, myInventory);
             }
             else if (CustomOrder.Order_Status__c == 'Picked' && CustomOrder.RemovedFromInventory__c == False) {
                 try{
                     CustomOrder.RemovedFromInventory__c = True;
                     myInventory = InventoryClass.removeFromInventoryList(CustomOrder.Product2__c, CustomOrder.quantity__c, myInventory);
                 }
                 catch (IllegalArgumentException e){
                     CustomOrder.addError('Cannot pick an item when there isn\'t enough inventory to cover it');
                 }
         	}
         }
          upsert myInventory;
	}
}