InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/Custom_Inventory__c.object-meta.xml
<CustomObject>
    <label>Custom Inventory</label>
    <nameField>
        <displayFormat>Inventory-ID-{000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Inventories</relationshipLabel>
    <relationshipName>Custom_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app 2/main/default/objects/Custom_Order__c/recordTypes/Picking.recordType-meta.xml
<RecordType>
    <fullName>Picking</fullName>
    <active>true</active>
    <label>Picking</label>
</RecordType>

InventoryManagement/force-app/main/default/objects/Product2/fields/Total_In_Stock__c.field-meta.xml
<CustomField>
    <fullName>Total_In_Stock__c</fullName>
    <label>Total In Stock</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Product2/fields/Total_Incoming__c.field-meta.xml
<CustomField>
    <fullName>Total_Incoming__c</fullName>
    <label>Total Incoming</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Product2/fields/Total_Outstanding__c.field-meta.xml
<CustomField>
    <fullName>Total_Outstanding__c</fullName>
    <label>Total Outstanding</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

InventoryManagement/force-app/main/default/classes/ProductClass.cls
public class ProductClass {
	
    // if add is false then subtracts
    public static void adjustProductSummariesBasedOnOrder(List<Custom_Order__c> orders, Boolean add) {
        List<Id> orderIds = OrderClass.getIdsFromOrders(orders);
        List<Id> orderProductIds = OrderClass.getProductIdsFromOrders(orders);
        
        Map<String, Schema.RecordTypeInfo> orderInfomation = Schema.sObjectType.Custom_Order__c.getRecordTypeInfosByName();
        
        List<Product2> products_tmp = [SELECT Id, Total_In_Stock__c, Total_Incoming__c FROM Product2];
        List<Custom_Order__c> ordersFullInfomation = [SELECT Id, Product2__R.Id, RecordTypeId, Order_Status__c, Quantity__c FROM Custom_Order__c WHERE id in :orderIds];
        List<Product2> products = [SELECT Id, Total_In_Stock__c, Total_Incoming__c, Total_Outstanding__c FROM Product2 WHERE Id in :orderProductIds];
        
        System.debug(products + 'Bob');
        System.debug(products[0].Total_In_Stock__c + 'Bob1');
        System.debug(products[0].Total_Incoming__c + 'Bob2');
        System.debug(products[0].Total_Outstanding__c + 'Bob3');
        
        for (Product2 product : products){
            System.debug(product.id + 'Test123 ');
            for (Custom_Order__c order : ordersFullInfomation) {
                if (product.Id == order.Product2__R.Id) {
                    if (order.RecordTypeId == orderInfomation.get('Inbound Order').getRecordTypeId() && order.Order_Status__c != 'Delivered'){
                        product.Total_Incoming__c = adjustValue(product.Total_Incoming__c, order.quantity__c, add);
                        System.debug(products[0].Total_Incoming__c + 'Bob4');
                    } else if (order.RecordTypeId == orderInfomation.get('Picking').getRecordTypeId() && order.Order_Status__c == 'Pending'){
                        product.Total_Outstanding__c = adjustValue(product.Total_Outstanding__c, order.quantity__c, add);
                    } 
                }
            }
        }
        
        System.debug(products + 'Bob5');
        update products;
        
    }  
    
    
    public static void adjustProductSummariesBasedOnInventoryChange(List<Custom_Inventory__c> newInventories, Boolean add) {
        System.debug('Changing invy');
        List<Id> newInvintoryIds = InventoryClass.getIdsFromInventories(newInventories);
        List<Id> newProductInvintoryIds = InventoryClass.getProductIdsFromInventories(newInventories);
		
        System.debug('Changing invy2' + newInvintoryIds + newProductInvintoryIds);
        List<Custom_Inventory__c> NewInvintoriesFullInfomation = [SELECT Id, Product2__R.Id, Quantity__c FROM Custom_Inventory__c WHERE id in :newInvintoryIds];
        List<Product2> products = [SELECT Id, Total_In_Stock__c, Total_Incoming__c, Total_Outstanding__c FROM Product2 WHERE Id in :newProductInvintoryIds];
        for (Product2 product : products){
            if (newInventories != null){
                for (Custom_Inventory__c newInventory : NewInvintoriesFullInfomation) {
                    System.debug('Changing invy3' + product  + newInventory);
                    if (product.Id == newInventory.Product2__R.Id) {
                        System.debug('Changing invy3.5' + product.Id + newInventory.Product2__R.Id + product  + newInventory);
                        product.Total_In_Stock__c = adjustValue(product.Total_In_Stock__c, newInventory.quantity__c, add);
                    }
                }
            }
        }
        System.debug('Updating invy4');
        update products;
    }
        
    
    public static void PreventDeleteIfUsed(List<Product2> products){ 
        List<id> product_ids = getProductIds(products);
        List<Custom_Order__c> orders = [SELECT id, Product2__R.id FROM Custom_Order__c WHERE Product2__R.id in :product_ids];
        List<Custom_Inventory__c> inventories = [SELECT id, Product2__R.id FROM Custom_Inventory__c WHERE Product2__R.id in :product_ids];
        
        for (Product2 product : products) {
            for (Custom_Order__c order : orders) {
                for (Custom_Inventory__c inventory : inventories) {
                    if (product.id == order.Product2__R.id || product.id == inventory.Product2__R.id ){
                        product.addError('Cannot remove products that are in orders or inventory');
                    }
                }
            }                
        }
    	
    }
    public static List<id> getProductIds(List<Product2> products){
        List<id> product_ids = new List<id>();
        for (Product2 product : products) {
                product_ids.add(product.id);
        }
        return product_ids;
    }
    
    public static Decimal adjustValue(Decimal value, Decimal quantity, Boolean add){
        if (add){
            if (value == null){
                value = quantity;
            }else {
                value += quantity;
            }
        } else {  // subtract
            if (value == null){
                value = quantity * -1;
            }else {
                value -= quantity;
            }
        }
        return value;
    }
    
}