InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/Custom_Inventory__c.object-meta.xml
<CustomObject>
    <label>Custom Inventory</label>
    <nameField>
        <displayFormat>Inventory-ID-{000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Inventories</relationshipLabel>
    <relationshipName>Custom_Inventories</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/Product2__c.field-meta.xml
<CustomField>
    <fullName>Product2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

InventoryManagement/force-app 2/main/default/objects/Custom_Order__c/recordTypes/Picking.recordType-meta.xml
<RecordType>
    <fullName>Picking</fullName>
    <active>true</active>
    <label>Picking</label>
</RecordType>

InventoryManagement/force-app/main/default/classes/TestOrder.cls
@isTest
public class TestOrder {
	@TestSetup
    Public static void MakeData() {
        TestHelper.MakeData();
    }
    
    @isTest
    public static void orderTriggerTest(){
        Test.startTest();
        List<Product2> newProducts = [SELECT id, Name from Product2];
        
        id inbound_order_id = Schema.sObjectType.Custom_Order__c.getRecordTypeInfosByName().get('Inbound Order').getRecordTypeId();
        id picking_id = Schema.sObjectType.Custom_Order__c.getRecordTypeInfosByName().get('Picking').getRecordTypeId();
        
        List<Custom_Order__c > new_Custom_Orders = new List<Custom_Order__c >();
        new_Custom_Orders.add(new Custom_Order__c (quantity__c=10, Product2__c=newProducts[0].Id, Order_Status__c='Delivered', RecordTypeId=inbound_order_id));
        new_Custom_Orders.add(new Custom_Order__c (quantity__c=10, Product2__c=newProducts[1].Id, Order_Status__c='picked', RecordTypeId=picking_id));
        new_Custom_Orders.add(new Custom_Order__c (quantity__c=10, Product2__c=newProducts[1].Id, Order_Status__c='pending', RecordTypeId=picking_id));
        
        insert new_Custom_Orders;
        
        Test.stopTest(); 
        
        List<Custom_Inventory__c> invitory1 = [SELECT quantity__c FROM Custom_Inventory__c WHERE Product2__c=:newProducts[0].Id LIMIT 1];
        List<Custom_Inventory__c> invitory2 = [SELECT quantity__c FROM Custom_Inventory__c WHERE Product2__c=:newProducts[1].Id LIMIT 1];
        
        System.assertEquals(30, invitory1[0].quantity__c);
        System.assertEquals(10, invitory2[0].quantity__c);
        
    }
}