InventoryManagement/force-app/main/default/objects/Custom_Inventory__c/Custom_Inventory__c.object-meta.xml
<CustomObject>
    <label>Custom Inventory</label>
    <nameField>
        <displayFormat>Inventory-ID-{000000}</displayFormat>
        <label>Inventory ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Inventories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

InventoryManagement/force-app 2/main/default/objects/Custom_Inventory__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Custom_Product__c</referenceTo>
    <relationshipLabel>Custom Inventories</relationshipLabel>
    <relationshipName>Custom_Inventories</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/Custom_Order__c.object-meta.xml
<CustomObject>
    <label>Custom Order</label>
    <nameField>
        <displayFormat>Order-id-{000000}</displayFormat>
        <label>Order ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Custom Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

InventoryManagement/force-app/main/default/objects/Custom_Order__c/fields/AddedToInventory__c.field-meta.xml
<CustomField>
    <fullName>AddedToInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Private field to add to inventory only once per order</description>
    <label>AddedToInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/Order_Status__c.field-meta.xml
<CustomField>
    <fullName>Order_Status__c</fullName>
    <label>Order Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>pending</fullName>
            </value>
            <value>
                <fullName>picked</fullName>
            </value>
            <value>
                <fullName>sent for delivery</fullName>
            </value>
            <value>
                <fullName>delivered</fullName>
            </value>
            <value>
                <fullName>returned</fullName>
            </value>
            <value>
                <fullName>canceled</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Returned to manufacture</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <referenceTo>Custom_Product__c</referenceTo>
    <relationshipLabel>Custom Orders</relationshipLabel>
    <relationshipName>Custom_Orders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/objects/Custom_Order__c/fields/RemovedFromInventory__c.field-meta.xml
<CustomField>
    <fullName>RemovedFromInventory__c</fullName>
    <defaultValue>false</defaultValue>
    <label>RemovedFromInventory</label>
    <type>Checkbox</type>
</CustomField>

InventoryManagement/force-app 2/main/default/objects/Custom_Order__c/recordTypes/Picking.recordType-meta.xml
<RecordType>
    <fullName>Picking</fullName>
    <active>true</active>
    <label>Picking</label>
</RecordType>

InventoryManagement/P1/force-app/main/default/objects/Custom_Product__c/Custom_Product__c.object-meta.xml
<CustomObject>
    <label>Custom Product</label>
    <nameField>
        <label>Product Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Custom Products</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

InventoryManagement/force-app 2/main/default/objects/Custom_Product__c/fields/price__c.field-meta.xml
<CustomField>
    <fullName>price__c</fullName>
    <label>price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

InventoryManagement/P1/force-app/main/default/classes/TestHelper.cls
@isTest
public class TestHelper {
	@testSetup
    Public static void MakeData() {
        List<Custom_Product__c> newProducts = new List<Custom_Product__c>();
        newProducts.add(new Custom_Product__c(Name='Oatmeal', Description__c='test product', price__c=20.20));
        newProducts.add(new Custom_Product__c(Name='Coffee', Description__c='test product', price__c=20.10)); 
        
        insert newProducts;
        
        newProducts = [SELECT id, Name, Description__c, price__c from Custom_Product__c];
        
        List<Custom_Inventory__c> new_Custom_Inventory = new List<Custom_Inventory__c>();
        new_Custom_Inventory.add(new Custom_Inventory__c(quantity__c=20, Product__c=newProducts[0].Id));
        new_Custom_Inventory.add(new Custom_Inventory__c(quantity__c=20, Product__c=newProducts[1].Id));
        
        insert new_Custom_Inventory;
        
        List<Custom_Order__c> new_Custom_Orders = new List<Custom_Order__c>();
        id inbound_order_id = Schema.sObjectType.Custom_Order__c.getRecordTypeInfosByName().get('Inbound Order').getRecordTypeId();
        id picking_id = Schema.sObjectType.Custom_Order__c.getRecordTypeInfosByName().get('Picking').getRecordTypeId();
        new_Custom_Orders.add(new Custom_Order__c (quantity__c=10, Product__c=newProducts[0].Id, Order_Status__c='Delivered', RecordTypeId=inbound_order_id, AddedToInventory__c=True, RemovedFromInventory__c=True));
        new_Custom_Orders.add(new Custom_Order__c (quantity__c=10, Product__c=newProducts[1].Id, Order_Status__c='Pending', RecordTypeId=picking_id, AddedToInventory__c=True, RemovedFromInventory__c=True));
        
        insert new_Custom_Orders;
        
        
        
            
    }
}